[package]

name = "banana"
version = "0.0.1"
authors = ["shockham <samuel.hockham@gmail.com>"]

[dependencies]
regex = "*"
bufstream = "*"

[dev-dependencies]
temple = { git = "https://github.com/shockham/temple.git" }
